spring:
  application:
    name: feign-consumer

server:
  port: 10201

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/

feign:
  hystrix:
    enabled: true