spring:
  application:
    name: web-app

server:
  port: 8081
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/

  instance:
    hostname: eureka-web
    instanceId: web-app:${server.port}