spring:
  application:
    name: eureka-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/

  instance:
    hostname: eureka-service-p1
    instanceId: ${eureka.instance.hostname}:${server.port}